name: Docker CI/CD

on:
  push:
    branches:
      - 'CI-branch-test'
    tags:
      - 'v*.*.*'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/pstake/Dockerfile
          push: true
          tags: 8857890900/pstake-native_test:latest
          build-args: |
            VERSION=${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image with tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/pstake/Dockerfile
          push: true
          tags: |
            8857890900/pstake-native_test:${{ github.ref_name }}
            8857890900/pstake-native_test:latest
          build-args: |
            VERSION=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
