name: CI Workflow for pstake-native with Matrix E2E Tests

on:
  pull_request:
    branches:
      - 'CI-branch-test' 
  push:
    branches:
      - 'CI-branch-test' 

env:
  IMAGE_NAME: pstaked-local
  IMAGE_TAG: latest
  TAR_PATH: pstaked-image.tar

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-e2e-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f cosmos/Dockerfile .
      
      - name: Save Docker image to tarball
        run: |
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} > ${{ env.TAR_PATH }}

      - name: Publish Tarball as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pstake-docker-image
          path: ${{ env.TAR_PATH }}

      - name: Setup Go with cache
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.5

      - name: Download dependencies for interchaintest
        run: |
          cd interchaintest && go mod download

  e2e-tests:
    needs: build-e2e-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - "e2e-test-basic"
          - "e2e-test-ibc-transfer"
      fail-fast: false

    steps:
      - name: Download Tarball Artifact
        uses: actions/download-artifact@v4
        with:
          name: pstake-docker-image

      - name: Load Docker Image
        run: |
          docker image load -i pstaked-image.tar

      - name: Setup Go with cache
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.5

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run test
        run: |
          export IMAGE_NAME=${{ env.IMAGE_NAME }}
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          make ${{ matrix.test }}
