name: CI Workflow for pstake-native with Matrix E2E Tests

on:
  pull_request:
    branches:
      - 'CI-branch-test' 
  push:
    branches:
      - 'CI-branch-test' 

env:
  IMAGE_NAME: pstaked-local
  IMAGE_TAG: latest
  TAR_PATH: pstaked-image.tar

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-e2e-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image with Heighliner
        uses: strangelove-ventures/heighliner-build-action@v0.0.3
        with:
          github-repo: "pstake-native-test"
          git-ref: ${{ steps.branch-name.outputs.current_branch }}
          chain: "pstake"
          dockerfile: "cosmos"
          build-target: make install
          binaries: |
            - /go/bin/pstaked
          build-env: |
            - "LEDGER_ENABLED=false"
            - "BUILD_TAGS=muslc"

          tag: local # emulate local environment for consistency in interchaintest cases
          tar-export-path: ${{ env.TAR_PATH }} # export a tarball that can be uploaded as an artifact for the e2e jobs
          platform: linux/amd64 # test runner architecture only

      - name: Publish Tarball as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pstake-docker-image
          path: ${{ env.TAR_PATH }}

      - name: Setup Go with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.21.5"

      - name: Download dependencies for interchaintest
        run: |
          cd interchaintest && go mod download

  e2e-tests:
    needs: build-e2e-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - "e2e-test-basic"
          - "e2e-test-ibc-transfer"
      fail-fast: false

    steps:
      - name: Download Tarball Artifact
        uses: actions/download-artifact@v4
        with:
          name: pstake-docker-image

      - name: Load Docker Image
        run: docker image load -i ${{ env.TAR_PATH }}

      - name: Setup Go with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: "1.21.5"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test
        run: make ${{ matrix.test }}
