name: CI Workflow for Docker Debugging

on:
  push:
    branches:
      - 'CI-branch-test'

jobs:
  docker-debug:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged
        ports:
          - 2375:2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Client
        run: |
          sudo mkdir -p /etc/docker
          echo '{"debug": true, "hosts": ["tcp://127.0.0.1:2375", "unix:///var/run/docker.sock"]}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

      - name: Verify Docker Client Configuration
        run: |
          docker version
          docker info

      - name: Build and Run a Simple Docker Image
        run: |
          docker run hello-world
